emenu/urls.py
from django.conf.urls import (url, include)
from emenu import views

app_name = 'emenu'
urlpatterns = [
    url(r'^$', views.EmenuView.as_view(), name='index'),
    url(r'^login/', views.LoginView.as_view(), name='login'),
    url(r'^logout/', views.LogoutView.as_view(), name='logout'),
    url(r'^menucard/', include(views.MenuCardViewSet().urls)),
    url(r'^dish/', include(views.DishViewSet().urls)),
    url(r'^category/', include(views.CategoryViewSet().urls)),
    url(r'^price/', include(views.PriceViewSet().urls)),
    url(
        r'^(?P<menucard_id>[0-9]+)/$',
        views.DishListView.as_view(),
        name='menu'
    ),
    url(
        r'^dish_nr/(?P<dish_id>[0-9]+)/$',
        views.DishDetailView.as_view(),
        name='dish_id'
    ),
    url(
        r'^(?P<menucard_id>[0-9]+)/dish_nr/(?P<dish_id>[0-9]+)/$',
        views.DishDetailView.as_view(),
        name='menu_dish'
    ),
]

emenu/models.py
from decimal import Decimal

from django.core.validators import MinValueValidator
from django.db import models
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _


class ImagePreview(object):
    def preview(self, obj):
        template = u"""<img src="{url}" style="max-height: {size};" />"""
        config = {
            'field': 'image',
            'size': '48px',
        }
        custom_config = getattr(self, 'set_preview', {})
        config.update(custom_config)
        image = getattr(obj, config['field'], None)
        url = image.url if image else ''
        return mark_safe(
            template.format(
                url=url,
                size=config['size'])
        )


class DateTimeInfoAbstract(models.Model):
    """
    abstract base class with auto generated fields
    """
    created_at = models.DateTimeField(
        _('created at'),
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        _('updated at'),
        auto_now=True
    )

    class Meta:
        abstract = True


class BaseInfoQuerySet(models.QuerySet):
    def active(self):
        """
        get list of active objects
        """
        return self.filter(active=True)


class BaseInfoAbstract(DateTimeInfoAbstract):
    objects = BaseInfoQuerySet.as_manager()
    name = models.CharField(
        _('name'),
        max_length=128,
        null=True,
        blank=True,
        unique=True
    )
    description = models.CharField(
        _('description'),
        max_length=650,
        blank=True,
        null=True,
    )
    is_active = models.BooleanField(
        _('active'),
        default=False
    )

    class Meta:
        app_label = 'emenu'
        abstract = True


class Currency(models.Model):
    code = models.CharField(
        _('code'),
        max_length=3,
        unique=True
    )
    name = models.CharField(
        _('name'),
        max_length=35
    )
    symbol = models.CharField(
        _('symbol'),
        max_length=4,
        blank=True
    )

    def __str__(self):
        return self.symbol

    class Meta:
        app_label = 'emenu'
        verbose_name = _('Currency')
        verbose_name_plural = _('Currencies')


class Price(models.Model):
    dish = models.ForeignKey(
        'Dish',
        verbose_name=_('dish'),
        blank=True,
        on_delete=models.CASCADE,
        related_query_name='price',
        related_name='prices',
    )
    currency = models.ForeignKey(
        Currency,
        verbose_name=_('currency'),
        blank=True,
        on_delete=models.CASCADE,
        related_name='price'
    )
    price = models.DecimalField(
        _('price'),
        default=0,
        decimal_places=2,
        max_digits=15,
        validators=[MinValueValidator(Decimal(0))],
        null=True,
        blank=True
    )

    def __str__(self):
        if self.currency:
            return u'%s %s' % (
                self.price,
                self.currency.symbol
            )
        else:
            return self.price

    class Meta:
        app_label = 'emenu'
        verbose_name = _('Price')
        verbose_name_plural = _('Prices')
        unique_together = ('dish', 'currency')

    def get_absolute_url(self):
        return reverse('emenu:price_change', kwargs={'pk': self.pk})


class Category(models.Model):
    title = models.CharField(
        _('title'),
        max_length=50,
        unique=True,
    )

    def __str__(self):
        return self.title

    class Meta:
        abstract = False
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')


class Dish(BaseInfoAbstract, ImagePreview):
    is_vegetarian = models.BooleanField(
        _('vegetarian'),
        default=False
    )
    preparation_time = models.PositiveSmallIntegerField(
        _('preparation time'),
        default=10
    )
    image = models.ImageField(
        _('image'),
        upload_to='dishes/',
        default='/emenu/no-image.png',
    )
    category = models.ForeignKey(
        Category,
        verbose_name=_('category'),
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_query_name='dish',
        related_name='dishes'
    )

    def __str__(self):
        return self.name

    class Meta:
        app_label = 'emenu'
        abstract = False
        verbose_name = _('Dish')
        verbose_name_plural = _('Dishes')


class MenuCardManagerQuerySet(models.QuerySet):
    def active(self):
        return self.filter(is_active=True)

    def not_empty(self):
        return self.exclude(dishes=None)


class MenuCardManager(models.Manager):
    def get_queryset(self):
        return MenuCardManagerQuerySet(
            self.model, using=self._db
        )

    def is_active(self):
        return self.get_queryset().active()

    def not_empty(self):
        return self.get_queryset().not_empty()


class MenuCard(BaseInfoAbstract):
    objects = MenuCardManager()

    image = models.ImageField(
        _('image'),
        upload_to='cards/',
        default='emenu/no-image.png',
    )
    dishes = models.ManyToManyField(
        Dish,
        verbose_name=_('dishes'),
        related_name='cards',
        related_query_name='card',
        blank=True
    )

    class Meta:
        app_label = 'emenu'
        abstract = False
        verbose_name = _('Menu Card')
        verbose_name_plural = _('Menu Card\'s')

    def get_absolute_url(self):
        return reverse('menucard', kwargs={'id': self.id})

    def __str__(self):
        return self.name

emenu/forms.py
from django import forms

from emenu import models


class CategoryForm(forms.ModelForm):

    class Meta:
        model = models.Category
        fields = (
            'title_en',
            'title_pl',
        )


class MenuCardForm(forms.ModelForm):

    class Meta:
        model = models.MenuCard
        fields = (
            'name_en',
            'description_en',
            'name_pl',
            'description_pl',
            'is_active',
            'image',
        )


class DishForm(forms.ModelForm):

    class Meta:
        model = models.Dish
        fields = (
            'name_en',
            'description_en',
            'name_pl',
            'description_pl',
            'category',
            'is_vegetarian',
            'is_active',
            'image'
        )

emenu/views/administration.py
from django.db import models
from django.db.models import Count
from django.utils.translation import gettext as _
from django.utils.translation import ugettext_lazy as _
from material import (
    Layout,
    Row,
    Fieldset
)
from material.frontend.views import (
    ModelViewSet,
)

from emenu.admin import (
    ImagePreviewAdmin,
)
from emenu.forms import (
    MenuCardForm,
    CategoryForm,
    DishForm,

)
from emenu.models import (
    MenuCard,
    Dish,
    Category,
    Currency,
    Price
)


class MenuCardViewSet(
    ImagePreviewAdmin,
    ModelViewSet
):
    model = MenuCard
    form_class = MenuCardForm

    ordering = ['id']
    list_display = (
        'id',
        'name',
        'is_active',
        'dish_count',
        'preview',
        'updated_at',
        'created_at',
    )
    list_display_links = ('id', 'name',)
    list_filter = ('is_active',)
    list_per_page = 10
    queryset = MenuCard.objects.all().annotate(
        dish_count=Count('dishes')
    )
    layout = Layout(
        Fieldset(
            _('Menu'),
            Row('name_en', 'name_pl'),
            'is_active',
            Row('description_en', 'description_pl')
        ),
    )

    def dish_count(self, obj):
        return obj.dish_count

    dish_count.admin_order_field = 'dish_count'
    dish_count.short_description = _('dishes')
    dish_count.allow_tags = True


class DishViewSet(ImagePreviewAdmin, ModelViewSet):
    model = Dish
    form_class = DishForm
    list_per_page = 1
    ordering = ['name']
    list_display = (
        'id',
        'name',
        'preview',
        'is_active',
        'is_vegetarian',
        'preparation_time',
        'category',
    )
    list_display_links = ('id',)
    list_filter = (
        'is_active',
        'is_vegetarian',
        'category',
    )


class CategoryViewSet(ModelViewSet):
    model = Category
    form_class = CategoryForm
    ordering = ['id']
    list_display_links = ['id', 'title_en', 'title_pl', ]
    list_display = ('id', 'title_en', 'title_pl', 'dish_count')
    queryset = Category.objects.all().annotate(
        dish_count=Count('dish')
    )
    layout = Layout(
        Fieldset(
            _('category name:'),
            Row('title_en', 'title_pl'),
        )
    )

    def dish_count(self, obj):
        return obj.dish_count

    dish_count.admin_order_field = 'dish_count'
    dish_count.short_description = _('dishes in category')
    dish_count.allow_tags = True


class CurrencyViewSet(ModelViewSet):
    model = Currency
    ordering = ['id']
    list_display_links = ['id', ]
    list_display = ('id', 'code', 'name', 'symbol')
    list_editable = ('code', 'name', 'symbol')

    dish = models.ForeignKey(
        'Dish',
        verbose_name=_('dish'),
        blank=True,
        on_delete=models.CASCADE,
        related_query_name='price',
        related_name='prices',
    )
    currency = models.ForeignKey(
        Currency,
        verbose_name=_('currency'),
        blank=True,
        on_delete=models.CASCADE,
        related_name='price'
    )


class PriceViewSet(ModelViewSet):
    model = Price
    list_display_links = [
        'price',
        'currency',
        'dish'
    ]
    list_display = (
        'dish',
        'price',
        'currency',
    )

emenu/views/public.py
from django.db.models import Count
from django.shortcuts import (
    get_object_or_404
)
from django.views.generic import (
    TemplateView,
    ListView
)
from material.frontend.views import (
    DetailModelView
)

from emenu.models import (
    MenuCard,
    Dish
)


class LogoutView(TemplateView):
    template_name = 'emenu/registration/logged_out.html'


class LoginView(TemplateView):
    template_name = 'emenu/registration/login.html'


class CustomListOrdering(object):
    """
    List ordering handler for generic List Views
    """

    def get_ordering(self):
        ordering_dict = dict(self.request.GET.items())
        self.order = ordering_dict.get('order', 'asc')
        self.ordering = ordering_dict.get('ordering', 'id')
        self.page = ordering_dict.get('page', '1')
        if self.order == 'desc':
            self.ordering = '-%s' % self.ordering
        return self.ordering


class EmenuView(CustomListOrdering, ListView):
    """
    [ e-Menu home page - public visible page ]
    show only "active" and not empty "MenuCards"
    """
    model = MenuCard
    template_name = 'emenu/index.html'
    paginate_by = 3
    queryset = MenuCard.objects.not_empty().active().annotate(
        dish_count=Count('dishes')
    )
    context_object_name = "object_list"

    def get_context_data(self, *args, **kwargs):
        context = super(EmenuView, self).get_context_data(*args, **kwargs)
        context['current_order'] = self.get_ordering()
        context['order'] = self.order
        context['query_count'] = self.queryset.count()
        return context


class DishListView(CustomListOrdering, ListView):
    model = Dish
    template_name = 'emenu/dish_list_page.html'
    paginate_by = 3
    queryset = Dish.objects.all()

    def get_context_data(self, **kwargs):
        context = super(
            DishListView, self
        ).get_context_data(**kwargs)
        context.update({
            'menucard': get_object_or_404(
                MenuCard,
                pk=self.kwargs.get('menucard_id')
            ),
            'current_order': self.get_ordering(),
            'order': self.order,
            'query_count': self.queryset.count(),

        })
        return context


class DishDetailView(DetailModelView):
    model = Dish
    template_name = 'emenu/dish_detail_page.html'

    def get_context_data(self, **kwargs):
        context = super(DishDetailView, self).get_context_data(**kwargs)
        context.update({
            'menucard_id': kwargs.get('menucard_id')
        })
        return context

    def get_object(self):
        self.object = get_object_or_404(
            Dish,
            id=self.kwargs.get('dish_id')
        )
        return self.object

emenu/templates/emenu/base.html
{% load i18n static material_form %}
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE|default:"en" }}">
    <head>
        {% block head %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
        <title>{% block title %}{% endblock %}</title>
        {% block favicon %}<link href="{% static 'material/imgs/favicon.png' %}" rel="shortcut icon">{% endblock %}
        {% block css %}{% include 'material/frontend/includes/material_css.html' %}{% endblock css %}
        {% block js %}{% include 'material/frontend/includes/material_js.html' %}{% endblock js %}
        {% block extrahead %}
        <link rel="stylesheet" type="text/css" href="{% static 'emenu/css/style.css' %}"/>
        {% endblock %}
        {% endblock head %}
    </head>
    <body class="{%block bodyclass %}with-sidebar{% endblock %}">
        {% block body %}
        <header>
            {% block header %}
            <ul id="slide-out" class="sidenav sidenav-fixed" data-turbolinks-permanent style="display:{% if user.is_authenticated %}block{% else %}none{% endif %};">
                {% block sidenav_header %}
                <li>
                    <div class="user-view">
                        <div class="background" >
                          <img src="{% static 'material/imgs/sidenav.svg' %}">
                        </div>
                        {% block userphoto %}
                        {% if user.photo.url %}
                        <a href="#"><img class="circle" src="{{ user.photo.url }}"></a>
                        {% else %}
                        <a href="#"><img class="circle" src="{% static 'material/imgs/user.png' %}"></a>
                        {% endif %}
                        {% endblock %}
                        <a href="#"><span class="white-text name">{{ request.user.get_username|title }}</span></a>
                        <a href="#"><span class="white-text email">{{ request.user.email }}</span></a>
                    </div>
                </li>
                {% endblock %}
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'logout' %}" data-turbolinks="false"><i class="material-icons right">exit_to_app</i>{% trans "Log out" %}</a></li>
                    {% else %}
                    <li><a href="{% url 'login' %}" data-turbolinks="false"><i class="material-icons right">lock_open</i>{% trans "Log in" %}</a></li>
                    {% endif %}
                {% block sidenav_items %}
                {% if user.is_authenticated %}
                {% for module in modules %}
                {% if current_module == module %}
                <li class="active">
                    <ul class="collapsible collapsible-accordion">
                        <li>
                            <a href="{{ module.index_url }}" class="collapsible-header active">{{ module.verbose_name }}{{ module.icon|safe }}</a>
                            <div class="collapsible-body" style="display:block">
                                {% include module.menu %}
                            </div>
                        </li>
                    </ul>
                </li>
                {% else %}
                <li {% if forloop.last %}class="last"{% endif %}>
                    <a href="{{ module.index_url }}" class="collapsible-header" data-turbolinks="false">{{ module.verbose_name }}{{ module.icon|safe }}</a>
                </li>
                {% endif %}
                {% endfor %}
                {% endif %}
                {% endblock sidenav_items %}
            </ul>
            {% endblock %}
        </header>
        <main style={% if user.is_authenticated %}'margin-left:300px'{% else %}'margin-left:0'{% endif %}>
            {% block main %}
            {% block topbar %}
            <nav class="topbar">
                <div class="nav-wrapper">
                    <a href="#" data-target="slide-out" class="sidenav-trigger"><i class="material-icons">menu</i></a>
                    <div class="brand-logo">
                        <a href="/">
                        {% block page_title %}e-Menu{% endblock %}
                        </a>
                    </div>
                    <ul id="nav-mobile" class="right hide-on-med-and-down">
                        {% block topbar_links %}
                        {% if user.is_authenticated %}
                        <li><a href="{% url 'logout' %}" data-turbolinks="false"><i class="material-icons right">exit_to_app</i>{% trans "Log out" %}</a></li>
                        {% else %}
                        <li><a href="{% url 'login' %}" data-turbolinks="false"><i class="material-icons right">lock_open</i>{% trans "Log in" %}</a></li>
                        {% endif %}
                        {% endblock %}
                    </ul>
                </div>
            </nav>
            {% endblock topbar %}
            {% block breadcrumbs %}
            <nav class="breadcrumbs">
                <div class="nav-wrapper">
                    {% block breadcrumbs_items %}{% endblock %}
                </div>
                 <div class="language-selector">{% include 'emenu/includes/language_selector.html' %}</div>
            </nav>
            {% endblock %}
            {% block main_content %}
            <div class="content">
                {% block content %}{% endblock %}
                {% block bottomcontent %}{% endblock %}
            </div>
            {% endblock main_content %}
            {% endblock main %}
        </main>
        <footer>
            {% block footer %}
            {% endblock footer %}
        </footer>
        {% endblock %}
        {% block messages %}
        {% if messages %}
        <script id="messages" type="text/javascript">
            $(document).one('turbolinks:load', function () {
              {% for message in messages %}
              M.toast({html: '{{ message|capfirst }}', displayLength: 10000, classes:'alert-{{ message.tags }}'})
              {% endfor %}
            });
        </script>
        {% endif %}
        {% endblock messages %}
    </body>
</html>

emenu/templates/emenu/dish_detail_page.html
{% extends 'emenu/index.html' %}
{% load i18n static admin_list %}

{% block title %}{% trans 'Dish' %}{% endblock %}
{% block jumbo %}
<div class="row col">
    <h1 class="display-3 text-md center">{% trans 'e-Menu' %}</h1>
    <p class="text-md center">{% trans 'Digital restaurant menu ' %}<strong> django </strong>app.</p>
</div>
<div class="row col">
    <h1 class="display-4 text-md center">{% trans 'dish:' %}<strong> {{ object.name }}</strong></h1>
    <script>function goBack() {
        window.history.back();
    }</script>
    <div class="col s12">
        <a style="margin-right:15px;" onclick="goBack()" class="btn btn-lg btn-primary white-text darken-1 left back-blue">
            {% trans 'go back' %}
        </a>
        <a href="{% url 'emenu:index' %}" class="btn btn-lg btn-secondary left back-blue">
            {% trans 'home page' %}
        </a>
    </div>
</div>
{% endblock jumbo %}

{% block left-panel %}
<div class="left-panel">
    <div class="card">
        <div class="card-content">
            {% block card %}
            <div class="card-title"><strong> {{ object.name }}</strong></div>

            <img class="responsive-img" src="{{ object.image.url }}">
            <table class="table">
                <tr>
                    <th><strong> {% trans 'is a vegetarian dish' %}:</strong></th>
                    <th class="left">
                        {% if object.is_vegetarian %}
                        <i class="left material-icons green600">check_circle</i>
                        {% else %}
                        <i class="material-icons red600">cancel</i>
                        {% endif %}
                    </th>
                </tr>
                <tr>
                    <th>{% trans 'preparation time' %}: </th>
                    <th><strong> {{ object.preparation_time }} {% trans 'minutes' %} </strong> </th>
                </tr>
                    <tr>
                        <th>
                    <strong> {% trans 'description' %}:</strong>

                        <p>{{ object.description }}</p>
                    </th>
                </tr>
            </table>
            {% endblock %}
        </div>
        <div class="card-action">
            <div class="right-align">
                {% block actions_row %}
                {% if delete_url %}<a class="waves-effect waves-light btn red white-text" href="{{ delete_url }}">{% trans 'Delete' %}</a>{% endif %}
                {% if change_url %}<a class="waves-effect waves-light btn white-text" href="{{ change_url }}">{% trans 'Change' %}</a>{% endif %}
                {% endblock actions_row %}
            </div>
        </div>
    </div>
</div>
{% endblock left-panel %}

emenu/templates/emenu/dish_list_page.html
{% extends 'emenu/index.html' %}
{% load i18n static admin_list %}

{% block title %}{% trans 'e-Menu' %}{% endblock %}
{% block jumbo %}
<h1 class="display-3 center">{% trans 'e-Menu' %}</h1>
<p class="center">{% trans 'Digital restaurant menu ' %}<strong> django </strong>app.</p>
<br><hr/>
<h1 class="display-5 center"><strong>{{ menucard.name }}</strong></h1><hr/>
<div class="row col">
    <a href="{% url 'emenu:index' %}" class="btn btn-primary white-text left back-blue">{% trans 'go back' %}</a>
    <h5 class="right">{% trans 'dishes in card' %}:<strong> {{ query_count }}</strong></h5>
</div>
{% endblock jumbo %}
{% block left-panel %}
<div class="left-panel">
    <div class="card list-card">
        <div class="card-content">
            {% if object_list %}
            <table id="table" class="table bordered" data-form-control="datatable" style="width:100%">
                <thead>
                <tr role="row">
                    <th data-name="id" class="id sorting" name="{% if ordering == 'id' %}current-order{% endif %}">
                        <strong>
                            <a href="{% url 'emenu:index' %}{{ menucard.pk }}?ordering=id&order={% if order == 'desc' %}asc{% else %}desc{% endif %}">
                                {% trans 'Id' %}
                            </a>
                        </strong>
                    </th>
                    <th data-name="name" class="name sorting" name="{% if ordering == 'name' %}current-order{% endif %}">
                        <strong>
                            <a href="{% url 'emenu:index' %}{{ menucard.pk }}?ordering=name&order={% if order == 'desc' %}asc{% else %}desc{% endif %}">
                                {% trans 'Name' %}
                            </a>
                        </strong></th>
                    <th data-name="is_active" class="is_active sorting" name="{% if ordering == 'is_active' %}current-order{% endif %}">
                        <strong>
                            <a href="{% url 'emenu:index' %}{{ menucard.pk }}?ordering=is_active&order={% if order == 'desc' %}asc{% else %}desc{% endif %}">
                                {%trans 'Active' %}
                            </a>
                        </strong>
                    </th>
                    <th data-name="category__title" class="category__title sorting" name="{% if ordering == 'category__title' %}current-order{% endif %}">
                        <strong>
                            <a href="{% url 'emenu:index' %}{{ menucard.pk }}?ordering=category&order={% if order == 'desc' %}asc{% else %}desc{% endif %}">
                                {%trans 'Categories' %}
                            </a>
                        </strong>
                    </th>
                    <th name="{% if ordering == 'image' %}current-order{% endif %}"><strong><a href="#">{% trans 'Photo' %}</a></strong></th>
                </tr>
                </thead>
                <tbody>
                {% for object in object_list %}
                    <tr>
                        <td><a href="{% url 'emenu:menu_dish' menucard_id=menucard.pk dish_id=object.id %}">{{ object.id }}</a>
                        <td><a href="{% url 'emenu:menu_dish' menucard_id=menucard.pk dish_id=object.id %}">{{ object.name }}</a></td>
                        <td><a href="{% url 'emenu:menu_dish' menucard_id=menucard.pk dish_id=object.id %}">{{ object.is_active }}</a></td>
                        <td><a href="{% url 'emenu:menu_dish' menucard_id=menucard.pk dish_id=object.id %}">{{ object.category }}</a></td>
                        <td class="field-preview"><img src="{{ object.image.url }}" style="max-height: 80px;">
                       </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
              {% include "emenu/includes/pagination.html" %}
            </div>
            {% else %}
                <h3>{% trans 'Dish list' %}</h3>
                <p>{% trans 'no dishes found!' %}</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock left-panel %}

emenu/templates/emenu/index.html
{% extends 'emenu/base.html' %}
{% load i18n static %}
{% block title %}{% trans 'e-Menu' %}{% endblock %}
{% block extrahead %}
{{ block.super }}
{% endblock %}

{% block main_content %}
<div class="container">
    <div class="jumbotron">
        {% block jumbo %}
        <h1 class="display-3 text-md center">{% trans 'e-Menu' %}</h1>
        <p class="text-md center">{% trans 'Digital restaurant menu ' %}<strong> django </strong>app.</p>
        <hr/><h5>{% trans 'available "Menu Card" list. Click a card name to see the content.' %}</h5>
        <p>{% trans 'the columns are sortable via column header click.' %}</p>
        <div class="row col">
            <h5 class="right">{% trans 'menus' %}:<strong> {{ object_list.count }}</strong></h5>
        </div>
        {% endblock jumbo %}
        {% block left-panel %}
        <div class="left-panel">
            <div class="card list-card">
                <div class="card-content">
                    {% if object_list %}
                    <table id="table" class="table bordered" data-form-control="datatable" style="width:100%">
                        <thead>
                        <tr role="row">
                            <th data-name="id" class="id sorting" name="{% if ordering == 'id' %}current-order{% endif %}">
                                <strong><a href="{% url 'emenu:index' %}?ordering=id&order={% if order == 'desc' %}asc{% else %}desc{% endif %}">
                                    {% trans 'Id' %}</a>
                                </strong>
                            </th>
                            <th data-name="name" class="name sorting" name="{% if ordering == 'name' %}current-order{% endif %}">
                                <strong><a href="{% url 'emenu:index' %}?ordering=name&order={% if order == 'desc' %}asc{% else %}desc{% endif %}">
                                    {% trans 'Menu Card' %}
                                </a>
                                </strong>
                            </th>
                            <th data-name="dish_count" class="dish_count sorting" name="{% if ordering == 'dish_count' %}current-order{% endif %}">
                                <strong>
                                    <a href="{% url 'emenu:index' %}?ordering=dish_count&order={% if order == 'desc' %}asc{% else %}desc{% endif %}">
                                    {%trans 'Dishes' %}
                                    </a>
                                </strong>
                            </th>
                            <th name="{% if ordering == 'image' %}current-order{% endif %}"><strong><a href="#">
                                {% trans 'Photo' %}
                            </a>
                            </strong>
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for object in object_list %}
                            <tr>
                                <td><a href="{{ object.id }}">{{ object.id }}</a></td>
                                <td><a href="{{ object.id }}">{{ object.name }}</a></td>
                                <td><a href="{{ object.id }}">{{ object.dish_count }}</a></td>
                                <td class="field-preview"><img src="{{ object.image.url }}" style="max-height: 80px;">
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                      {% include "emenu/includes/pagination.html" %}
                    </div>
                    {% else %}
                        <h3>{% trans 'Menu cards' %}</h3>
                        <p>{% trans 'no menus found!' %}</p>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endblock left-panel %}
    </div>
    <br>
    <p><a class="btn btn-primary btn-lg btn-block back-blue " href="https://bitbucket.org/michal-frackowiak-mfx/emenu" role="button"><strong><i class="material-icons md-48">face</i>{% trans 'Go to repo »' %}</strong></a></p>
{% endblock main_content %}

emenu/templates/emenu/menu.html
{% load i18n %}
<ul class="left-menu">
    <li><a href="{% url 'emenu:index' %}"><span class="i-grey"> <i class="material-icons">home</i></span> {% trans 'Home' %}</a></li>
    <li><a href="{% url 'emenu:menucard_list' %}"><span class="i-grey"><i class="material-icons">view_agenda</i></span>{% trans 'Cards' %}</a></li>
    <li><a href="{% url 'emenu:category_list' %}"><span class="i-grey"><i class="material-icons">view_list</i></span>{% trans 'Categories' %}</a></li>
    <li><a href="{% url 'emenu:dish_list' %}"><span class="i-grey"><i class="material-icons">view_headline</i></span>{% trans 'Dishes' %}</a></li>
    <li><a href="{% url 'emenu:price_list' %}"><span class="i-grey"><i class="material-icons">euro_symbol</i></span>{% trans 'Prices' %}</a></li>
    <li><a href="{% url 'admin:index' %}"><span class="i-grey"> <i class="material-icons">settings</i></span>{% trans 'Admin' %}</a></li>
</ul>